
version: 2

models:
  - name: stg_users 
    description: "Contains users information"
    columns:
      - name: user_id
        tests:
            - unique
            - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id

  - name: stg_addresses 
    description: "Contains addresses information"
    columns:
      - name: address_id
        tests:
              - unique
              - not_null
      - name: address
      - name: zipcode
      - name: state
      - name: country

  - name: stg_events 
    description: "Contains events information"
    columns:
      - name: event_id
        tests:
            - unique
            - not_null
      - name: session_id
      - name: user_id
      - name: event_type
      - name: page_url
      - name: created_at

  - name: stg_orders 
    description: "Contains orders information"
    columns:
      - name: order_id
        tests:
            - unique
            - not_null
      - name: promo_id
      - name: user_id
      - name: address_id
      - name: created_at
      - name: order_cost
        tests:
          - positive_values
      - name: shipping_cost
        tests:
          - positive_values
      - name: order_total
        tests:
          - positive_values
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status


  - name: stg_order_items 
    description: "Contains order_items information"
    columns:
      - name: order_id
      - name: product_id
      - name: quantity
        tests:
          - positive_values

  - name: stg_products 
    description: "Contains products information"
    columns:
      - name: product_id
        tests:
            - unique
            - not_null
      - name: name
      - name: price
        tests:
          - positive_values
      - name: quantity
        tests:
          - positive_values

  - name: stg_promos 
    description: "Contains promos information"
    columns:
      - name: promo_id
      - name: discount
        tests:
          - positive_values
      - name: status